services:
  agentify-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentify-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${EXPOSE_PORT:-3050}:${PORT:-3000}
